### ISSUE TITLE
Failed to exec lerna:install script when running npm install

### ISSUE THREAD

**Issue by ronaldlong46** [worldsibu/convector-cli#10]
System:
Ubuntu 18.04
Node.js 8.12.0

Error log when running 'npm i':
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lerna:install' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prelerna:install', 'lerna:install', 'postlerna:install' ]
5 info lifecycle Test@0.1.0~prelerna:install: Test@0.1.0
6 info lifecycle Test@0.1.0~lerna:install: Test@0.1.0
7 verbose lifecycle Test@0.1.0~lerna:install: unsafe-perm in lifecycle true
8 verbose lifecycle Test@0.1.0~lerna:install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/bud/Convector/Test/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-$
9 verbose lifecycle Test@0.1.0~lerna:install: CWD: /home/bud/Convector/Test
10 silly lifecycle Test@0.1.0~lerna:install: Args: [ '-c', 'lerna bootstrap' ]
11 silly lifecycle Test@0.1.0~lerna:install: Returned: code: 1  signal: null
12 info lifecycle Test@0.1.0~lerna:install: Failed to exec lerna:install script
13 verbose stack Error: Test@0.1.0 lerna:install: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Test@0.1.0
15 verbose cwd /home/bud/Convector/Test
16 verbose Linux 4.15.0-36-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "lerna:install"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error Test@0.1.0 lerna:install: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the Test@0.1.0 lerna:install script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by walmon** [comment]
Thanks for your report @ronaldlong46 we have an environment that matches your current settings so we will check it out ASAP to see what is happening. I'll keep you posted. Just in case maybe some packages were corrupt, could you please retry running ´npm i´?

**Comment by walmon** [comment]
Closing due to inactivity
